document.addEventListener("DOMContentLoaded", () => {
    const factText = document.getElementById("fact");
    const generateBtn = document.getElementById("generate-btn");
    const darkModeBtn = document.getElementById("dark-mode-btn");
    const darkModeIcon = darkModeBtn.querySelector("i");

    const facts = [
        "A group of flamingos is called a 'flamboyance'.",
        "Bananas are berries, but strawberries aren't.",
        "Honey never spoils. Archaeologists have found pots of honey in ancient tombs that are over 3000 years old and still edible.",
        "A day on Venus is longer than a year on Venus.",
        "Octopuses have three hearts and blue blood.",
        "Wombat poop is cube-shaped to prevent it from rolling away.",
        "If you yelled for 8 years, 7 months, and 6 days, you would produce enough sound energy to heat a cup of coffee.",
        "You can't hum while holding your nose (try it!).",
        "A bolt of lightning is five times hotter than the surface of the sun.",
        "There’s a species of jellyfish that is biologically immortal.",
        "Scotland has 421 words for 'snow'.",
        "A shrimp's heart is located in its head.",
        "The shortest war in history was between Britain and Zanzibar on August 27, 1896. It lasted 38 to 45 minutes.",
        "The Eiffel Tower can grow taller in the summer due to heat expansion.",
        "Water can boil and freeze at the same time under the right conditions, called the 'triple point'.",
        "The word 'strengths' is the longest English word with only one vowel.",
        "Some turtles can breathe through their butts.",
        "If you shuffle a deck of cards, there’s a high chance that exact order has never existed before in history.",
        "There's an island in Japan full of rabbits called 'Rabbit Island'.",
        "A small child could swim through the veins of a blue whale.",
        "Butterflies taste with their feet.",
        "Butterflies can’t fly if they’re too cold.",
        "Mosquitoes are more attracted to people who just ate bananas.",
        "A crocodile can't stick its tongue out.",
        "It rains diamonds on Jupiter and Saturn.",
        "Cows have best friends and get stressed when they are separated.",
        "Sloths can hold their breath longer than dolphins can.",
        "Sharks existed before trees.",
        "There's a basketball court on the top floor of the U.S. Supreme Court building called \"The Highest Court in the Land\".",
        "A day on Mars is only 37 minutes longer than a day on Earth.",
        "A bolt of lightning contains enough energy to toast 100,000 slices of bread.",
        "A flea can jump 350 times its body length.",
        "The dot over the letter 'i' is called a \"tittle.\"",
        "There's a fish called the 'Sarcastic Fringehead'.",
        "The average person will spend six months of their life waiting for red lights to turn green.",
        "The smell of freshly-cut grass is actually a plant distress signal.",
        "Dolphins have been observed using pufferfish toxins to get high.",
        "The longest recorded hiccup spree lasted 68 years.",
        "A group of porcupines is called a 'prickle'.",
        "Birds don't urinate.",
        "Some cats are allergic to humans.",
        "Ants never sleep.",
        "There are more fake flamingos in the world than real ones.",
        "The Empire State Building has its own zip code (10118).",
        "There's a town in Norway where the sun doesn't set for 76 days in summer.",
        "Humans share about 60% of their DNA with bananas.",
        "You can hear a blue whale’s heartbeat from over 2 miles away.",
        "Sea otters hold hands while sleeping to keep from drifting apart.",
        "Cows have best friends and get stressed when separated.",
        "If you lift a kangaroo's tail off the ground, it can’t hop.",
        "Snails have thousands of microscopic teeth on their tongue.",
        "A group of crows is called a \"murder\".",
        "There's a species of fungus that turns ants into zombies.",
        "Penguins propose to their mates by presenting them with a perfect pebble.",
        "The inventor of the microwave oven got the idea after a chocolate bar melted in his pocket.",
        "Cats have a special purring frequency that helps them heal faster.",
        "A strawberry isn't actually a berry, but an avocado is.",
        "A full head of human hair is strong enough to support 12 tons.",
        "Bees can recognize human faces.",
        "Koalas have fingerprints that are nearly indistinguishable from humans'.",
        "You can’t burp in space because there’s no gravity to separate liquid from gas in your stomach.",
        "A group of ferrets is called a 'business'.",
        "If you folded a piece of paper 42 times, it would be thick enough to reach the moon.",
        "Cows moo in regional accents.",
        "Jellybeans are coated in shellac, which is made from insect secretions.",
        "The longest wedding veil was longer than 63 football fields.",
        "There's a lake in Australia that is naturally bright pink.",
        "A goldfish’s memory span is longer than three seconds – it’s actually several months.",
        "Banging your head against a wall burns 150 calories per hour (but I don’t recommend it).",
        "Goats have rectangular pupils.",
        "A group of pugs is called a 'grumble'.",
        "A snail can sleep for three years.",
        "There is an underwater waterfall in the ocean near Mauritius.",
        "Cows produce more milk when they listen to relaxing music.",
        "Coca-Cola would be green if coloring wasn’t added.",
        "The inventor of the Pringles can is now buried in one.",
        "Tigers have striped skin, not just striped fur.",
        "Walt Disney was afraid of mice.",
        "You are always about half an inch taller in the morning than at night.",
        "Your heart beats about 100,000 times per day.",
        "It’s impossible to sneeze with your eyes open.",
        "No number before 1,000 contains the letter 'A' when spelled out in English.",
        "Bananas glow blue under black light.",
        "It takes about 8 minutes for light from the sun to reach Earth.",
        "The total weight of ants on Earth is close to the total weight of humans.",
        "You can’t taste food properly without saliva.",
        "A jellyfish doesn’t have a brain, heart, or bones.",
        "Apples float in water because they are 25% air.",
        "It's physically impossible for pigs to look up into the sky.",
        "Cows have nearly 360-degree vision.",
        "A blob of toothpaste is called a nurdle.",
        "Otters use rocks as tools.",
        "One-quarter of your bones are in your feet.",
        "Water makes up around 70% of your body.",
        "A cat’s meow is reserved for communicating with humans, not other cats.",
        "The first oranges weren’t orange; they were green.",
        "There’s a species of turtle that breathes through its butt.",
        "The world’s largest desert isn’t the Sahara—it’s Antarctica.",
        "Cows can walk upstairs but not downstairs.",
        "Sloths can take up to a month to digest a single meal.",
        "A baby octopus is about the size of a flea when it is born.",
        "Most wasabi in stores is actually just dyed horseradish.",
        "The unicorn was the national animal of Scotland long before the U.S. was a country.",
        "Avocados were named after testicles (the Aztec word \"āhuacatl\").",
        "The word, \"Hippopotomonstrosesquippedaliophobia\" means fear of long words.",
        "Pigeons can recognize themselves in a mirror.",
        "A peanut is not a nut—it’s a legume.",
        "A strawberry isn't a berry, but a watermelon is.",
        "The Cookie Monster’s real name is Sid.",
        "Wombats are the only animals that produce cube-shaped poop.",
        "The inventor of the lava lamp was inspired by an egg timer.",
        "The first recorded instance of someone saying “OMG” was in 1917.",
        "Pineapples take about two years to grow.",
        "The inventor of roller skates debuted them by crashing into a mirror.",
        "Armadillo shells are bulletproof.",
        "You can’t taste food as well if you hold your nose.",
        "A group of jellyfish is called a \"smack.\"",
        "An octopus has nine brains but no bones.",
        "The Guinness World Record for holding one’s breath underwater is over 24 minutes.",
        "The smell of Play-Doh is patented.",
        "The world’s shortest commercial flight lasts only 57 seconds.",
        "There’s a McDonald’s on every continent except Antarctica.",
        "Giraffes only need 5 to 30 minutes of sleep per day.",
        "A day on Mercury is longer than a year on Mercury.",
        "The inventor of the frisbee was turned into a frisbee when he died.",
        "Some fish communicate by farting.",
        "Hippo sweat is pink.",
        "The first email was sent in 1971.",
        "There’s an island in Japan where only cats live.",
        "Elephants can’t jump.",
        "The fingerprints of koalas are nearly identical to humans'.",
        "If you cut a starfish in half, it might grow into two starfish.",
        "A cornflake once sold on eBay for $1,350 because it looked like Illinois.",
        "Some sea cucumbers can liquefy their bodies to fit into tiny spaces.",
        "The hashtag symbol (#) is technically called an octothorpe.",
        "The official average color of space is called \"cosmic latte.\"",
        "The moon gets about 1.5 inches farther from Earth every year.",
        "Vending machines kill more people per year than sharks.",
        "In 1518, there was a dancing plague where people danced uncontrollably for days.",
        "The entire world’s population could fit inside Los Angeles.",
        "It would take 19 minutes to fall to Earth’s core.",
        "Dolphins have names for each other.",
        "There’s a type of frog that breaks its own bones to make claws.",
        "If you eat too many carrots, your skin can actually turn orange.",
        "The letter \"J\" wasn’t added to the alphabet until the 1500s.",
        "Blue-eyed people share a common ancestor.",
        "A group of owls is called a “parliament.”",
        "The average cloud weighs about a million pounds.",
        "Bubble wrap was originally meant to be wallpaper.",
        "You blink about 20 times per minute.",
        "A hedgehog’s heart beats 300 times per minute.",
        "A giraffe's tongue is about 20 inches long.",
        "The word “nerd” was first used in a Dr. Seuss book.",
        "A single strand of spaghetti is called a \"spaghetto.\"",
        "The inventor of the Rubik’s cube took a month to solve it.",
        "There’s an island in Canada called \"Dildo.\"",
        "The average human has enough bones in their body to make a second skeleton by the age of 25.",
        "Technically, the longest English word is 189,819 letters long and takes over three hours to pronounce. It refers to the full chemical name of titin, the largest known protein",
        "A blob of toothpaste is called a nurdle.",
        "The Bible is the most shoplifted book in the world.",
        "A jellyfish’s body is 95% water.",
        "The shortest war in history lasted only 38-45 minutes.",
        "The moon has moonquakes.",
        "The world's oldest piece of chewing gum is over 9,000 years old.",
        "The total weight of all ants on Earth is close to the total weight of all humans.",
        "Turtles can feel through their shells.",
        "The scientific term for brain freeze is \"sphenopalatine ganglioneuralgia.\"",
        "Peanuts can be made into dynamite.",
        "Sloths can turn their heads almost 360 degrees.",
        "Humans have a small tailbone because we once had tails.",
        "Some frogs can freeze solid in the winter and thaw out in the spring.",
        "There's a fish that can change its gender multiple times throughout its life.",
        "Newborn babies can’t cry real tears for the first few weeks.",
        "Most people dream in color, but some dream in black and white.",
        "Your bones are about five times stronger than steel.",
        "There are more public libraries in the U.S. than McDonald's restaurants.",
        "A hummingbird weighs less than a penny.",
        "A strawberry has more vitamin C than an orange.",
        "There’s an official Wizard of New Zealand appointed by the government.",
        "The fastest recorded sneeze was 100 mph."
    ];

    // Generate a random fact
    generateBtn.addEventListener("click", () => {
        factText.textContent = facts[Math.floor(Math.random() * facts.length)];
    });

    // Function to toggle dark mode
    function toggleDarkMode() {
        document.body.classList.toggle("dark-mode");

        // Change icon
        if (document.body.classList.contains("dark-mode")) {
            darkModeIcon.classList.remove("fa-moon");
            darkModeIcon.classList.add("fa-sun");
            localStorage.setItem("darkMode", "enabled");
        } else {
            darkModeIcon.classList.remove("fa-sun");
            darkModeIcon.classList.add("fa-moon");
            localStorage.setItem("darkMode", "disabled");
        }
    }

    // Load saved dark mode state
    if (localStorage.getItem("darkMode") === "enabled") {
        document.body.classList.add("dark-mode");
        darkModeIcon.classList.remove("fa-moon");
        darkModeIcon.classList.add("fa-sun");
    }

    // Event listener for dark mode button
    darkModeBtn.addEventListener("click", toggleDarkMode);
});